config/routes.rb
Rails.application.routes.draw do

  root 'homepage#index'

  get 'abouttheartists' => 'abouttheartists#index' 

  get 'contact' => 'contact#index' 
  get 'gallery' => 'gallery#index' 

end

app/controllers/abouttheartists_controller.rb
class AbouttheartistsController < ApplicationController
	def index

	end

end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
	def index

	end

end

app/controllers/gallery_controller.rb
class GalleryController < ApplicationController
	def index

	end

end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
	def index

	end

end

app/views/abouttheartists/index.html.erb
<div class="navbar">
	<ul class="navbar-ul-left">
		<li>Ilizwi Lam</li>
	</ul>
	<ul class="navbar-ul-right">
		<li><%= link_to "contact us", contact_path %></li>
		<li class="nav-artists-tab"><%= link_to "about the artists", abouttheartists_path %></li>
		<li><%= link_to "gallery", gallery_path %></li>
		<li><%= link_to "home", root_path %></li>
	</ul>
</div>
<div class="container">
	<hr></hr>
	<div class="artists-header">about the artists</div>
	<hr></hr>
	<div class="row">
		<div class="four columns">
			<div class="artist-pic"><%= image_tag("https://s3.amazonaws.com/illizwilam/images/Abongile.JPG", id: "Abongile", :class => 'circular lazy') %></div>
		</div>
		<div class="eight columns">
			<div class="artist-name">Abongile Mbemba</div>
			<div class="artist-bio">I am Abongile Mbemba from a small township called Nyanga East in Zwelitsha. I was born in 1992. I have faced so many challenges. Being raised by unemployed parents, I have had to stand up for myself in order to have what I need. I used to be involved in bad things just to have something to do, but I managed to get back on a good path and be someone in my community. When I joined Etafeni it was because I wanted to be positive about life. Etafeni helped me stick to my promise to find a purpose. This Photovoice project helped me find love, because I have fallen in love with photography. I wanted to be a journalist since I was little, and now have so many dreams that I want to pursue.</div>
		</div>
	</div>
	<hr></hr>

	<div class="row">
		<div class="four columns">
			<div class="artist-pic"><%= image_tag("https://s3.amazonaws.com/illizwilam/images/Akhona.JPG", id: "Akhona", :class => 'circular lazy') %></div>
		</div>
		<div class="eight columns">
			<div class="artist-name">Akhona Khube</div>
			<div class="artist-bio">I’m Akhona Khube, and I live in Nyanga East in Zwelitsha. When I went to primary school there was a battle of personal finances, and so I had to change schools many times. Eventually I went to a school in Claremont where I finished my grade 12. I live with my mother, son, and sister in a one-room shack. I think that most jobs are now looking for experience, so some of us have no experience. That is the main battle of the process of getting a job. The best thing about my community is the love we have for one other. We are strong and help each other when there is a need.</div>
		</div>
	</div>
	<hr></hr>

	<div class="row">
		<div class="four columns">
			<div class="artist-pic"><%= image_tag("https://s3.amazonaws.com/illizwilam/images/Celiwe.JPG", id: "Celiwe", :class => 'circular lazy') %></div>
		</div>
		<div class="eight columns">
			<div class="artist-name">Celiwe Tshemese</div>
			<div class="artist-bio">I am Celiwe Tshemese. I was born in the Eastern Cape. At that time my parents were still alive.In 2006 my mother got very sick and passed away, and my father took my siblings and I to the Western Cape with him until he passed away in 2009. I have learned that in everything it is possible to be happy if you make your life meaningful. Though I face many challenges in life, that doesn't stop me from reaching out for what I believe in.</div>
		</div>
	</div>
	<hr></hr>

	<div class="row">
		<div class="four columns">
			<div class="artist-pic"><%= image_tag("https://s3.amazonaws.com/illizwilam/images/Cindy.JPG", id: "Cindy", :class => 'circular lazy') %></div>
		</div>
		<div class="eight columns">
			<div class="artist-name">Cindy Ralarala</div>
			<div class="artist-bio">I live in Gugulethu, and was born here in Cape Town. My father and my mother are originally form the Eastern Cape. I was 19 years old, and passed my matric last year with Diploma. I was surprised to get a Diploma. I like to listen to music, especially hip-hop. Right now I want a job to renovate my mothers house.</div>
		</div>
	</div>
	<hr></hr>

	<div class="row">
		<div class="four columns">
			<div class="artist-pic"><%= image_tag("https://s3.amazonaws.com/illizwilam/images/NontobekoJamjam.jpg", id: "Nontobeko Jamjam", :class => 'circular lazy') %></div>
		</div>
		<div class="eight columns">
			<div class="artist-name">Nontobeko Jamjam</div>
			<div class="artist-bio">I grew up in the Eastern Cape in a family of five. I passed my matric and went to Lovedale College to do my Performing Arts and Drama Certificate for two years. After that I worked at the Grahamstown Arts Festival until the contract expired. Then I came to Cape Town to hustle for jobs. I love dance and acting and want to spend my whole life in the arts.</div>
		</div>
	</div>
	<hr></hr>

	<div class="row">
		<div class="four columns">
			<div class="artist-pic"><%= image_tag("https://s3.amazonaws.com/illizwilam/images/Mkhululi.JPG", id: "Mkhululi", :class => 'circular lazy') %></div>
		</div>
		<div class="eight columns">
			<div class="artist-name">Mkhululi Shiba</div>
			<div class="artist-bio">My name is Mkhululi Shiba. I am 28 years old. My challenge in life is access resources—being able to fund my dream of having a dry wall company. I want to give back to the community and to be able to uplift it. This Photovoice project was educational for me, and I am starting to make a positive change in my life. I am looking forward to the challenges and achievements of seeing my community in a different way.</div>
		</div>
	</div>
	<hr></hr>

	<div class="row">
		<div class="four columns">
			<div class="artist-pic"><%= image_tag("https://s3.amazonaws.com/illizwilam/images/NtombekhayaJakuja.JPG", id: "Ntombekhaya Jakuja", :class => 'circular lazy') %></div>
		</div>
		<div class="eight columns">
			<div class="artist-name">Ntombekhaya Jakuja</div>
			<div class="artist-bio">My name is Ntombekhaya Jakuja. I’m 19 years old living in Cape Town in a township calledNyanga. I was born here in Nyanga and I was raised here by my single mother, who I love very much. I did my matric last year in 2013 and I passed. Growing up I have faced a lot of challenges, but some amazing things have happened in my life. In 2011 I won the award of Highest Achiever in Physical Sciences. During my school years, before finishing my matric, I was involved in a group of photography as an activity after school. My mentor was a professional journalist. In ten years time I want to see myself owning my own business, highly educated, achieving my goals, and making sure that I make my mother proud in everything that I do.</div>
		</div>
	</div>
	<hr></hr>

	<div class="row">
		<div class="four columns">
			<div class="artist-pic"><%= image_tag("https://s3.amazonaws.com/illizwilam/images/NtombekhayaLubinda.JPG", id: "Ntombekhaya Lubinda", :class => 'circular lazy') %></div>
		</div>
		<div class="eight columns">
			<div class="artist-name">Ntombekhaya Lubinda</div>
			<div class="artist-bio">I was born in 1989. The challenges that I faced in life growing up with an alcoholic mother were large, but I left her house and went to stay with my father and grandmother. I have a beautiful daughter, and my dream is to become a professional nurse and provide for my family. I want to give my child a brighter future and not have her suffer like I did. This Photovoice project made me realize how to handle life challenges and think outside of the box. Being a part of this exhibition was amazing because people can now get to see the pictures of the township life.</div>
		</div>
	</div>
	<hr></hr>

	<div class="row">
		<div class="four columns">
			<div class="artist-pic"><%= image_tag("https://s3.amazonaws.com/illizwilam/images/Ncebakazi.JPG", id: "Ncebakazi", :class => 'circular lazy') %></div>
		</div>
		<div class="eight columns">
			<div class="artist-name">Ncebakazi Mqolombeni</div>
			<div class="artist-bio">My name is Ncebakazi Mqolombeni. I am 24 years old and I was matriculated in 2011. I am agood person who understands people problems. I want people to take me seriously. If I am telling you about myself, when I was out of high school in 2013 I was not studying because of financial problems at home. My mother passed away when I was very young, but in all of these difficult problems I will persevere because I am happy with my father and siblings.</div>
		</div>
	</div>
	<hr></hr>

	<div class="row">
		<div class="four columns">
			<div class="artist-pic"><%= image_tag("https://s3.amazonaws.com/illizwilam/images/Noluthando.JPG", id: "Noluthando", :class => 'circular lazy') %></div>
		</div>
		<div class="eight columns">
			<div class="artist-name">Ncebakazi Mqolombeni</div>
			<div class="artist-bio">My name is Noluthando Gibisela. I was born in 1992. I live in Gugulethu with my grandmotherand two brothers. We are originally from Northern Cape (Kimberly). I studied in Crystal High School for my high school years. I am a kind, loving, caring, determined and optimistic person. I like sports such as netball, watching movies, and reading books. My mother passed away in a car accident in 2012. That was the most painful experience I have ever had, but with support I managed to get through it. My dream is to be in the hospitality business or to become a teacher. My short-term goal is to enroll in a university next year.</div>
		</div>
	</div>
	<hr></hr>

	<div class="row">
		<div class="four columns">
			<div class="artist-pic"><%= image_tag("https://s3.amazonaws.com/illizwilam/images/Phatiswa.JPG", id: "Phatiswa", :class => 'circular lazy') %></div>
		</div>
		<div class="eight columns">
			<div class="artist-name">Phatiswa Pikini</div>
			<div class="artist-bio">My name is Phatiswa Pikini. I am living with my parents. I am the first-born child. I have gone through challenges in my life, falling in love with somebody who was not good for me and having a family early in life. Teenagers like to experience things for themselves and don't want to be told what to do, but I have learned so many lessons in my life. I am curious about the next phase of my life and am a hard working woman.</div>
		</div>
	</div>
	<hr></hr>

	<div class="row">
		<div class="four columns">
			<div class="artist-pic"><%= image_tag("https://s3.amazonaws.com/illizwilam/images/Sandisile.JPG", id: "Sandisile", :class => 'circular lazy') %></div>
		</div>
		<div class="eight columns">
			<div class="artist-name">Sandisile Xelelwa</div>
			<div class="artist-bio">I was born in King William’s Town in Eastern Cape. I past my matric in 2004 and went toChrysalis Academy and then started looking for a job. Since then I joined the army of struggle (gangsterism), but realized that it was not the life that I was supposed to live. So I became responsible for my life. I want to provide for my family and am still hustling. This project is one of the best opportunities and has helped me to become a cameraman. My dream is to become a successful man with a family. I want to have a permanent job.</div>
		</div>
	</div>
	<hr></hr>

	<div class="row">
		<div class="four columns">
			<div class="artist-pic"><%= image_tag("https://s3.amazonaws.com/illizwilam/images/Thulani.JPG", id: "Thulani", :class => 'circular lazy') %></div>
		</div>
		<div class="eight columns">
			<div class="artist-name">Thulani Hasane</div>
			<div class="artist-bio">I am nineteen years old. I live in Philippi here in Cape Town. Originally I am from the Eastern Cape in the town called Umtata. I passed grade 12 in 2013. I like to read books and work. I am a hard worker—I can learn fast and like to improve myself in my free time. I grew up in the rural areas. Since I passed matric I have been busy applying for schools, am still looking. Now it is hard to find a job, because of internet access and skills to attract employers. Currently I am looking for a learnership for a job that I can get in order to gain money to prepare myself to go back to school. One of the challenges that I overcame was finishing with grade 12 even with all of the financial problems that my family. I focused on my books and did not involve myself in fancy things, drinking alcohol, or smoking.</div>
		</div>
	</div>
	<hr></hr>

	<div class="row">
		<div class="four columns">
			<div class="artist-pic"><%= image_tag("https://s3.amazonaws.com/illizwilam/images/Yolanda.JPG", id: "Yolanda", :class => 'circular lazy') %></div>
		</div>
		<div class="eight columns">
			<div class="artist-name">Yolanda Nqodi</div>
			<div class="artist-bio">I grew up in the Eastern Cape with my grandmother after my mother left me to go to Johannesburg to work. It was difficult for her to put me through school, but I came to Cape Town to study. I failed only Grade 12 when I fell pregnant, but am a hard worker and want to go back to school to continue my studies.</div>
		</div>
	</div>
	<hr></hr>
</div>

app/views/contact/index.html.erb
<div class="navbar">
	<ul class="navbar-ul-left">
		<li>Ilizwi Lam</li>
	</ul>
	<ul class="navbar-ul-right">
		<li class="nav-contact-tab"><%= link_to "contact us", contact_path %></li>
		<li><%= link_to "about the artists", abouttheartists_path %></li>
		<li><%= link_to "gallery", gallery_path %></li>
		<li><%= link_to "home", root_path %></li>
	</ul>
</div>
<div class="container">
	<hr></hr>
	<div class="contact-header">contact us</div>
	<hr></hr>
	<div class="contact-float-left">
		<div class="contact-myvoice-header">Ilizwi Lam</div>
		<div class="contact-myvoice-body">Thank you so much for visiting the Ilizwi Lam online exhibition and for using this time to engage with the inspiring and inspired work of the photographers. This project was independently managed, and could not have happened without the cooperation of Etafeni and its generous staff. <br></br>If you have any questions, comments, or suggestions, please e-mail <%= mail_to "Ilizwietafeni@gmail.com" %>.  If you would like to learn more about Etafeni, please visit their website at <%= link_to "etafeni.org", "http://www.etafeni.org" %> </div>
		<%= image_tag("https://s3.amazonaws.com/illizwilam/images/contactus.png", id: "Contact Us Image", :class =>'contact-group-pic lazy') %>
	</div>
	<div class="contact-float-right">
		<div class="contact-etafeni-header">Etafeni</div>
		<div class="contact-etafeni-info">CONTACT US</div>
		<br></br>
		<div class="etafeni-contact-text"><%= image_tag("https://s3.amazonaws.com/illizwilam/images/locationicon.png", id: "Location Icon", height: 50, width: 15, :class =>'etafeni-icon lazy') %>Sihume Road, Nyanga, Cape Town 7750</div>
		<div class="etafeni-contact-text"><%= image_tag("https://s3.amazonaws.com/illizwilam/images/timeicon.png", id: "Time Icon", height: 50, width: 15, :class =>'etafeni-icon lazy') %><strong>Tel:</strong> &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp021 386 1516</div>
		<div class="etafeni-contact-text"><%= image_tag("https://s3.amazonaws.com/illizwilam/images/faxicon.png", id: "Fax Icon", height: 50, width: 15, :class =>'etafeni-icon lazy') %><strong>Fax:</strong> &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp021 386 2560</div>
		<br>
		<div class="etafeni-contact-text"><strong>Peter Barendse</strong> (Project Manager)</div>
		<div class="etafeni-contact-text"><%= image_tag("https://s3.amazonaws.com/illizwilam/images/emailicon.svg", id: "Email Icon", height: 50, width: 15, :class =>'etafeni-icon lazy') %><strong>Email:</strong> &nbsp&nbsp&nbsp&nbsp&nbsp <%= mail_to "peter@etafeni.org.za" %></div>
		<br>
		<div class="etafeni-contact-text"><strong>Barbara Miller</strong> (Development Manager)</div>
		<div class="etafeni-contact-text"><%= image_tag("https://s3.amazonaws.com/illizwilam/images/timeicon.png", id: "Time Icon", height: 50, width: 15, :class =>'etafeni-icon lazy') %><strong>Tel:</strong> &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp082 890 2555</div>
		<br>
		<div class="etafeni-contact-text"><strong>Stephanie Kilroe</strong></div>
		<div class="etafeni-contact-text"><%= image_tag("https://s3.amazonaws.com/illizwilam/images/timeicon.png", id: "Time Icon", height: 50, width: 15, :class =>'etafeni-icon lazy') %><strong>Tel:</strong> &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp082 4621 082</div>
		<div class="etafeni-contact-text"><%= image_tag("https://s3.amazonaws.com/illizwilam/images/emailicon.svg", id: "Email Icon", height: 50, width: 15, :class =>'etafeni-icon lazy') %><strong>Email:</strong> &nbsp&nbsp&nbsp&nbsp&nbsp <%= mail_to "stephanie@intermail.co.za" %></div>
	</div>
</div>

app/views/homepage/index.html.erb
<div class="home-background"></div>
<div class="home-title">Ilizwi Lam</div>
<p class="home-paragraph">Ilizwi Lam is an exhibition of photos that were collected during a Photovoice project conducted among unemployed youth in Nyanga, Cape Town. Between July and August of 2014, participants of a life and work readiness skills programme at Etafeni, a community resource centre for people affected by HIV/AIDS, were given digital cameras and asked to capture things in the community that demand change, represent development, or that are sources of inspiration to the photographer in his/her journey to finding a job. Themes of entrepreneurship and self-reliance as well as the destructive effects of gang violence and alcohol emerge throughout the exhibit’s photographs and equally important accompanying captions.<br></br>Photovoice is a community engaged participatory research method that asks participants to represent their environment in a way that is expressible to community outsiders.  The goal of Ilizwi Lam is to share the voices and artwork of the brave participating students in a space where people can come to new realizations about the staggering beauty and persistent hardships that characterize life in Cape Town’s surrounding communities. The ultimate message of the photographs is one of inspiration and tangible hope for a life governed by the intrinsic power of the photographer’s voices.</p>
<div class="button-wrapper"><button type="button" class="home-enter-button"><%= link_to "Enter Site", gallery_path %></div></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyVoice</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>